#!/bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Framework          
#            --------------------------------------------------
#        Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
#    Ehtools framework (DO NOT COPY!)
#    
#    
#    About Author :
#    
#    Founder : Entynetproject (Ivan Nikolsky)
#    Instagram : @entynetproject | @ehtools_framework
#    Email : entynetproject@gmail.com
#    Project's site : https://entynethacker.wixsite.com/ehtools
#    Entynetproject's site : http://entynetproject.simplesite.com/
#

DPIDDD=$$
echo $DPIDDD > /root/ehtools/dpiddd.txt
i=1
delay="$Del"
if [[ "$delay" == "" ]]
then
	delay=5
fi
while [[ "$i" == 1 ]]
do
	TEMP=$(pyrit -r "$HANDCAP" analyze 2>/dev/null)
	TEMPHANDD=$(echo "$TEMP" | grep "good")
	TEMPHAND=$(echo "$TEMP" | grep "workable")
	if [[ "$TEMPHANDD" == "" && "$TEMPHAND" == "" ]]
	then
		printf "."	
	else
		clear
		echo -e "HANDSHAKE FOUND!"
		sleep 2
		echo -e "Exiting terminals..."
		sleep 1
		if [[ -f "$EPATH"/dpid.txt ]]
		then
			read DPID < "$EPATH"/dpid.txt
			PIF=$(ps -A | grep "$DPID")
			if [[ "$PIF" != "" ]]
			then
				kill $DPID
			fi
		fi
		break
	fi
	sleep "$delay"
done
j=1
while true
do
	PIDSE="dpid"$j".txt"
	if [[ -f "$EPATH"/"$PIDSE" ]]
	then
		read DPID < "$EPATH"/"$PIDSE"
		PIF=$(ps -A | grep "$DPID")
		if [[ "$PIF" != "" ]]
		then
			kill $DPID
		fi
	else
		rm "$EPATH"/dpid*
		break
	fi
	j=$((j+1))
done
if [[ -f "$EPATH"/dpidd.txt ]]
then
	read DPID2 < /root/ehtools/dpidd.txt
	kill -INT $DPID2
fi
exit

